### PR TITLE
Use ngchm api

### PR DESCRIPTION
**Pull request by bmbroom**

### CODE REVIEW

**Comment by bmbroom** [comment]
This pull request uses the additional API functions provided by the NG-CHM system.

Note: this pull request builds on the #37 pull request, which has not been merged yet. The first bunch of commits all belong to that pull request. Hopefully, they'll just go away when that branch is merged. In the meantime, please ignore them here.

**Comment by bmbroom** [comment]
Note: should not be merged until after the corresponding pull request has been merged into the NG-CHM repo, the needed NG-CHM artifacts have been updated in this repo, and the version numbers have been bumped.

**Review by jmelott — APPROVED** [review]

**Comment by ChrisWakefield** [comment]
>> Note: should not be merged until after ...
It sounds like this should be a draft PR.

@jmelott review of #40 requesting changes that are really about #37 that he submitted.  The changes were requested in #37 months back, so is that PR being abandoned in favor of these newer ones?

**Comment by bmbroom** [comment]
I built on the branch in that commit, so those commits appear at the start of this pull request, but I was intending for James to continue with his pull request first, then we can merge this pull request on top of that.

I think this was the first time I did that. The lack of feedback about building on branches in previous pull requests was why I starting making explicit commits about that in other pull requests.

**Pull request merged**
