### PR TITLE
Update to use newer supported version of tomcat official build.

### LINKED ISSUE #72: Update version of Tomcat to supported version.
The version of Tomcat used in the current docker container is no longer supported for security updates.
Updating the base tomcat container to tomcat:10.1.13-jdk17-temurin-jammy should fix the issue.

### PR DESCRIPTION
**Pull request by jmelott**
fixes #72

### CODE REVIEW

**Comment by marohrdanz** [comment]
I notice on lines 15 and 16 of the Dockerfile there are 'COPY --from=tomcat', but there is no 'tomcat' in the multistage build. Going back in the history, at some point there was a tomcat stage: https://github.com/MD-Anderson-Bioinformatics/NG-CHM_GUI_BUILDER/commit/1733b962d8559ae250da8e8d3ce28eba4c6c88d9

Does this give any error or warning when when the image builds?

If those tomcat jar files are no longer needed, we should remove these lines.

**Review by marohrdanz — CHANGES_REQUESTED** [review]
Something should be done about the 'COPY --from=tomcat' lines.

**Review by ChrisWakefield — APPROVED** [review]
After the additional changes.

**Review by marohrdanz — APPROVED** [review]
Looks as we discussed.

**Pull request merged**
